# Generated by Django 5.2.9 on 2026-01-02 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('agrodealer', 'Agrodealer'), ('agrovet', 'Agrovet'), ('veterinary_clinic', 'Veterinary Clinic')], default='agrodealer', max_length=30)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('inventory_tags', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_code', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=20)),
                ('nonchem_recommendations', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('published', models.BooleanField(default=False)),
                ('safety_flag', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_recs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('chemical', 'Chemical'), ('organic', 'Organic'), ('cultural', 'Cultural'), ('preventive', 'Preventive')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('active_ingredient', models.CharField(blank=True, max_length=255)),
                ('dose_text', models.TextField(blank=True)),
                ('application_method', models.CharField(blank=True, max_length=200)),
                ('pre_harvest_interval', models.CharField(blank=True, max_length=100)),
                ('ppe', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=400)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='recommendations.recommendation')),
            ],
        ),
    ]
